spring.datasource.url=${SOFTWARECUP_DB_URL:jdbc:postgresql://localhost:5432/softwarecup}
spring.datasource.username=${SOFTWARECUP_DB_USER:softwarecup}
spring.datasource.password=${SOFTWARECUP_DB_PASSWORD:softwarecup}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.h2.console.enabled=false
